"""Export module — download answers as Markdown or PDF."""

import io
import datetime


def export_markdown(messages: list[dict]) -> str:
    """Export chat history as Markdown."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    md = f"# Cognify — Research Session\n\n"
    md += f"**Exported:** {now}\n\n---\n\n"
    
    for msg in messages:
        if msg["role"] == "user":
            md += f"## 💬 Question\n\n{msg['content']}\n\n"
        elif msg["role"] == "assistant":
            md += f"## 🧠 Answer\n\n{msg['content']}\n\n"
            
            # Add sources if available
            if msg.get("sources"):
                md += "### 📚 Sources\n\n"
                for src in msg["sources"]:
                    md += f"- **{src['source']}** (p.{src['page']}): {src['text'][:200]}...\n"
                md += "\n"
            
            if msg.get("total_time"):
                md += f"*Response time: {msg['total_time']}*\n\n"
            
            md += "---\n\n"
    
    md += "\n*Generated by [Cognify](https://github.com/kulharir7/cognify) — Multi-Agent Document Intelligence*\n"
    return md


def export_single_answer(question: str, answer: str, sources: list = None, trace: list = None) -> str:
    """Export a single Q&A as Markdown."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    md = f"# Cognify Research Report\n\n"
    md += f"**Date:** {now}\n\n---\n\n"
    md += f"## Question\n\n{question}\n\n"
    md += f"## Answer\n\n{answer}\n\n"
    
    if sources:
        md += "## Sources\n\n"
        for src in sources:
            md += f"- **{src['source']}** (p.{src['page']})\n"
            md += f"  > {src['text'][:300]}\n\n"
    
    if trace:
        md += "## Agent Reasoning Trace\n\n"
        for step in trace:
            md += f"### {step['agent']} ({step.get('time', '?')})\n"
            md += f"{step['action']}\n\n"
    
    md += "\n---\n*Generated by Cognify*\n"
    return md
